# Generated by CodiumAI
from protinfo.cli import pi_parser
import pytest


class TestPiParser:
    def test_parser_initialization(self):
        """Verify that the parser correctly initializes with the program name 'ProtInfo'"""
        parser = pi_parser()
        assert parser.prog == "ProtInfo", "The program name should be initialized as 'ProtInfo'"

    def test_fetch_only(self):
        parser = pi_parser()
        with pytest.raises(SystemExit):
            parser.parse_args(["--fetch"])

    def test_empty_pdb_input(self):
        """Test empty string input for 'pdb' to see if it is handled or raises an error"""
        parser = pi_parser()
        with pytest.raises(SystemExit):
            parser.parse_args([])

    def test_long_pdbid(self):
        """Test input strings significantly longer than allowed."""
        parser = pi_parser()
        long_input = "A" * 10
        args = parser.parse_args([long_input])
        assert args.pdb is None, "The parser should return None for pdbid != 4."

    def test_long_pdb_name(self):
        """Test longname allowed for pdb file passed to pdb."""
        parser = pi_parser()
        long_input = "A" * 12 + ".pdb"
        args = parser.parse_args([long_input])
        assert args.pdb == long_input, "The parser should return the given pdb file name."
